production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "newpassword") %>
  host: <%= ENV.fetch("MYSQL_HOST", "host.docker.internal") %>
  port: <%= ENV.fetch("MYSQL_PORT", "3306") %>
  database: <%= ENV.fetch("MYSQL_DATABASE", "myapp_development") %>
  
